import { headers } from 'next/headers'
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Journal",
    description: "Generated by create next app",
};

export default async function Journal() {
    const h = await headers()
    const userId = h.get("userId")
    return <>
        <p>Welcome {userId}</p>
        <p>See below today&apos;s journal</p>
    </>
}