import { Metadata } from "next";
import styles from "./page.module.css";
import Journal from "../components/journal"
import { getUserInfo } from "../utils/actions";
import IconNavigation from "../components/icon-navigation";

export const metadata: Metadata = {
    title: "Journal",
    description: "Generated by create next app",
};

export default async function JournalPage() {
    const { displayName } = await getUserInfo()

    return <section className={styles.page}>
        <hgroup className={styles.greeting}>
            <h1>Welcome,</h1>
            <h2>{displayName}</h2>
        </hgroup>
        <section className={styles.entries}>
            <Journal />
        </section>
        <section className={styles.footer}>
            <IconNavigation active="journal" />
        </section>
    </section>
}