import styles from "./page.module.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
    <div className={styles.page}>
      <p>Hello, world</p>
    </div>
    </>
  );
}
