import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Login",
    description: "Generated by create next app",
};

export default function Journal() {
    return <p>Login please</p>
}