name: PR Checks
on:
  pull_request:
    branches:
      - "main"

env:
  AWS_REGION: eu-west-1
  AWS_ACCOUNT: 390403855196

jobs:
  synth:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm i

      - name: Install CDK dependencies
        working-directory: cdk
        run: npm i

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/GithubActionsAssumeRole
          aws-region: ${{ env.AWS_REGION }}

      - name: test role
        run: aws sts get-caller-identity

      - name: synth
        working-directory: cdk
        env:
          AWS_ENVIRONMENT: DEV
          AWS_ACCOUNT: ${{ env.AWS_ACCOUNT }}
        run: npx cdk synth --no-bundling